[package]
name = "regexml"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
enum_dispatch = "0.3.12"
icu_properties = "1.4.0"

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml", "glob"] }
