[package]
name = "regexml-ucd-blocks"
version = "0.1.0"
edition = "2021"
authors = ["Regexml contributors"]
description = "Maintain blocks.rs in regexml"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
